### ISSUE TITLE
Group Names/Description don't wrap and go off the screen

### ISSUE THREAD

**Issue by AshtonSparx** [vrcx-team/VRCX#482]
![Screenshot 2023-02-09 152816](https://user-images.githubusercontent.com/53165730/217929665-4d367c2a-3eff-4de4-b0bb-c12cdfdce501.png)

**Comment by Myrkie** [comment]
huh I was under the impression this was fixed long ago, do you happen to be using the latest stable version, im on nightly and it works as expected
![image](https://user-images.githubusercontent.com/20288698/217930015-3939a469-cfd9-4a74-955b-2c89fdd371d5.png)

**Comment by AshtonSparx** [comment]
I'm currently on the latest version and i have to guess, the special characters don't abide by the wrapping rules because the amongus still doesn't wrap on version 2023.02.18 

The group is owned by mystеrial (They have a special character for the e) if you wanna have a look
